[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  skip_processors_after_aggregators = false
  omit_hostname = true

[global_tags]
  robot_id = "${ROBOT_ID}"

[[inputs.cpu]]
[[inputs.mem]]

[[inputs.influxdb_v2_listener]]
  service_address = ":8087"
  token = "${DOWNSTREAM_INFLUXDB_TOKEN}"

[[outputs.influxdb_v2]]
  urls = [
    "${UPSTREAM_INFLUXDB_URL}"
  ]
  token = "${UPSTREAM_INFLUXDB_TOKEN}"
  organization = "${UPSTREAM_INFLUXDB_ORG}"
  bucket = "${UPSTREAM_INFLUXDB_BUCKET}"
