/**:
  ros__parameters:
    influx:
      url: "http://localhost:8087"
      org: ""
      bucket: ""
      token: "my-super-secret-auth-token"

    writer:
      max_batch: 1000
      max_queue: 100000
      flush_ms: 5000
      use_gzip: true

    mappings_ids:
      - imu

    imu:
      topic: "/imu"
      translator: "robot_influx_common_interfaces::ImuTranslator"
      measurement: "imu"
      max_rate: 200.0
      qos_history: keep_last
      qos_depth: 10
      qos_reliability: best_effort
      qos_durability: volatile
      tag_keys:
        - frame_id=imu_link
