/**:
  ros__parameters:
    influx:
      url: "http://localhost:8087"
      org: ""
      bucket: ""
      token: "my-super-secret-auth-token"

    writer:
      max_batch: 1000
      max_queue: 100000
      flush_ms: 5000
      use_gzip: true

    mappings_ids:
      - imu
      - tf_map

    imu:
      topic: "/imu"
      translator: "robot_influx_common_interfaces::ImuTranslator"
      measurement: "imu"
      max_rate: 200.0
      qos_history: keep_last
      qos_depth: 10
      qos_reliability: best_effort
      qos_durability: volatile
      tag_keys:
        - frame_id=imu_link
    tf_map:
      topic: ""
      translator: "robot_influx_common_interfaces::TfBasicTranslator"
      measurement: "tf"
      max_rate: 0.0
      qos_history: keep_last
      qos_depth: 10
      qos_reliability: reliable
      qos_durability: volatile
      tag_keys:
        - frame_id=map
      custom_config:
        - source_frame=base_link
        - target_frame=map
        - parent_frame=odom
        - buffer_time_sec=10.0
        - lookup_timeout_sec=0.1
        - frequency_hz=50.0
